# Generated by Django 4.2.6 on 2023-10-22 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bettingapp', '0002_client_delete_person'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='fullname',
            new_name='name',
        ),
    ]
